<?php
require_once 'CP.php';$RULE = 999;
if (!isset($_GET['venue_id'])) {
    header("Location: 404.phtml");
}
$SIGN_IN = FALSE;
if (isset($_COOKIE['EMAIL']) && $_COOKIE['EMAIL'] != '') {
    $SIGN_IN = TRUE;
    $EMAIL = filter_input(INPUT_COOKIE, 'EMAIL');
    $RULE = filter_input(INPUT_COOKIE, 'RULE');
    $NAME = filter_input(INPUT_COOKIE, 'NAME');
    $ID = filter_input(INPUT_COOKIE, 'ID');

    //venues data
    //$MyVenues = db_get_venues($ID);
}
$VENUE = db_get_venue($_GET['venue_id']);
if($VENUE==0){
    header("Location: 404.phtml");
}

$Booker_Name = "Your Name";
$Booker_From = "From";
$Booker_To = "To";
$Booker_Email = "Your Email";
$Booker_Phone = "Your Phone";
$message = '';
if(isset($_POST['submit_book'])){
    $Booker_Name = filter_input(INPUT_POST, 'NAME');
    $Booker_From = filter_input(INPUT_POST, 'FROM');
    $Booker_To = filter_input(INPUT_POST, 'TO');
    $Booker_Email = filter_input(INPUT_POST, 'EMAIL');
    $Booker_Phone = filter_input(INPUT_POST, 'PHONE');
    
    $message = db_check_book($Booker_Name,$Booker_From,$Booker_To,$Booker_Email,$Booker_Phone);
    
    if($message == 'success' && $VENUE){
        $message = db_book($Booker_Name,$Booker_From,$Booker_To,$Booker_Email,$Booker_Phone,$VENUE);
        if($message == 'success'){
            header("Location: venue_list.phtml");
        }
    }
}
if (isset($_POST['mSendemail'])) {
    $mName = filter_input(INPUT_POST, 'mName');
    $mEmail = filter_input(INPUT_POST, 'mEmail');
    $mMessage = filter_input(INPUT_POST, 'mMessage');

    db_send_message($mName, $mEmail, $mMessage);
}
?>

<html dir="ltr" lang="en-US">
    <head>

        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width" />

        <title>Wizme | Book it</title>

        <!-- [favicon] begin -->
        <link rel="shortcut icon" type="image/x-icon" href="images/favicon.ico" />
        <link rel="icon" type="image/x-icon" href="images/favicon.ico" />
        <!-- [favicon] end --> 

        <!-- CSS Main -->
        <link rel="stylesheet" type="text/css" media="all" href="css/reset.css" />
        <link rel="stylesheet" type="text/css" media="all" href="css/style.css" />
        <link rel="stylesheet" type="text/css" media="screen and (max-width: 960px)" href="css/lessthen960.css" />
        <link rel="stylesheet" type="text/css" media="screen and (max-width: 600px)" href="css/lessthen600.css" />
        <link rel="stylesheet" type="text/css" media="screen and (max-width: 480px)" href="css/lessthen480.css" />
        <link rel="stylesheet" type="text/css" media="all" href="css/memento.css"  />

        <!-- CSS Plugin -->
        <link rel="stylesheet" href="css/prettyPhoto.css" type="text/css" media="all" />
        <link rel="stylesheet" href="css/tipsy.css" type="text/css" media="all" />
        <link rel='stylesheet' href='css/buttons.min.css' type='text/css' media='all' />
        <link rel='stylesheet' href='css/labels.min.css' type='text/css' media='all' />
        <link rel='stylesheet' href='css/wells.min.css' type='text/css' media='all' />

        <!-- CSS Slider -->
        <link rel="stylesheet" href="css/slider-thumbnails.css" type="text/css" media="all" />

        <link rel="stylesheet" type="text/css" media="all" href="css/homes/home.css" />
        <link rel="stylesheet" type="text/css" media="all" href="css/login_style.css" />

        <!-- FONTS -->
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Droid+Sans&amp;subset=latin%2Ccyrillic%2Cgreek&amp;ver=3.4.1" type="text/css" media="all" />
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Shadows+Into+Light&amp;subset=latin%2Ccyrillic%2Cgreek&amp;ver=3.4.1" type="text/css" media="all" />
        <link rel='stylesheet' href='http://yourinspirationweb.com/demo/memento/wp-content/themes/memento/core/includes/css/font-awesome.css?ver=3.4.1' type='text/css' media='all' />
        <link rel='stylesheet' href='http://yourinspirationweb.com/demo/memento/wp-content/themes/memento/fonts/socialico/stylesheet.css?ver=3.4.1' type='text/css' media='all' />
        <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed%3A300%7CPlayfair+Display%3A400italic&#038;ver=3.4.1' type='text/css' media='all' />

        <!-- JavaScripts -->
        <script type="text/javascript">
            var yiw_prettyphoto_style = 'pp_default';
        </script>
        <script type="text/javascript" src="js/jquery.js"></script>
        <script type="text/javascript" src="js/jquery.cycle.min.js"></script>
        <script type="text/javascript" src="js/jquery.easing.1.3.js"></script>
        <script type="text/javascript" src="js/jquery.prettyPhoto.js"></script>
        <script type="text/javascript" src="js/jquery.tipsy.js"></script>
        <script type="text/javascript" src="js/jquery.tweetable.js"></script>
        <script type="text/javascript" src="js/jquery.nivo.slider.pack.js"></script>
        <script type="text/javascript" src="js/jquery.flexslider.min.js"></script>
        <script type="text/javascript" src="js/jquery.aw-showcase.js"></script>
        <script type="text/javascript" src="js/superfish.js"></script>
        <script type='text/javascript' src="js/jquery.eislideshow.js"></script>
        <script type='text/javascript' src="js/swfobject.js"></script>
        <script type='text/javascript' src='js/jquery.cookie.js'></script>
        <script type='text/javascript' src='js/buttons.min.js'></script>
        <script type='text/javascript' src='js/layerslider.kreaturamedia.jquery-min.js'></script>
        <script type='text/javascript' src='js/jquery.quicksand.js'></script>

    </head>
    <body class="no_js responsive boxed-layout chrome ">

        <!-- TOPBAR -->
        <div id="topbar">
            <div class="inner group">

                <div class="topbar-left">
                    <!-- START TWITTER -->
                    <div id="twitter-slider" class="group">
                        <div class="tweets-list"></div>
                        <script type="text/javascript" src="js/twitter.js" ></script>	
                    </div>
                    <!-- END TWITTER -->
                </div>

                <div class="topbar-right">
                    <ul class="topbar-level-1">
                        <?php
                        if ($SIGN_IN) {
                            echo '                               
                            <li class="login_link"><i class="icon-key"></i><a href="profile.phtml"> Profile(' . $NAME . ') </a></li>
                            <li class="login_link"><i class="icon-key"></i><a href="signout.php"> SignOut </a></li>';
                        } else {
                            echo '
                                <li class="login_link"><i class="icon-key"></i><a href="login.phtml"> Login </a></li>
                                <li class="login_link"><i class="icon-key"></i><a href="signup.phtml"> SignUp </a></li>'
                            ;
                        }
                        ?>
                    </ul>
                </div>

            </div>
        </div>
        <!-- END TOPBAR -->

        <!-- START WRAPPER -->
        <div class="wrapper group">
            <!-- START HEADER -->
            <div id="header" class="group">
                <div class="group inner">

                    <!-- START LOGO -->
                    <div id="logo" class="group">
                        <h1>
                            <a class="logo-text" href="index.phtml">Wiz<span>m</span>e</a>                        
                        </h1>
                        <p>THE PLACE WHERE MEETING ROOMS AND CUSTOMERS MEET</p>
                    </div>
                    <!-- END LOGO -->  

                    <!-- START NAV -->
                    <div id="nav" class="group">
                        <ul id="menu-main-nav" class="level-1">
                             <li>
                                <a href="index.phtml"><i class="icon-home"></i>Home</a>

                            </li>
                            
                             <li>
                                <a href="venue_list.phtml"><i class="icon-file"></i>Venues</a>

                            </li>
                            
                            <?php
                            if($SIGN_IN){
                                   echo ' <li>
                                <a href="newvenue.phtml"><i class="icon-picture"></i> Create Venue</a>

                            </li>';
                               }
                                if($RULE == 1){
                                    echo '<li>
                                <a href="venue_req.phtml"><i class="icon-film"></i>Requests</a>

                            </li>';
                                }
                            ?>
                            <li>
                                <a href="http://malloboany.blogspot.com"><i class="icon-calendar"></i>Blog</a>
                            </li>
                        </ul>
                    </div>
                    <!-- END NAV -->     
                </div>
            </div>
            <!-- END HEADER -->

            <!--  Log in Form  -->
            <!-----start-main---->
            <div class="header-map" style="background:url(images/backgrounds/005.jpg)  no-repeat center fixed;">
                <div class="center" >
                    <div class="clear"><br><br></div>
                    <div class="header-map"style="width: 50%">
                     <?php
                if ($VENUE ) {
                        echo' <div class="btn-large" >
                            <h2><i class="icon-envelope"></i> ' . $VENUE['Venue_Name'] . '</h2>
                            <p>' . db_get_kind_name($VENUE['Venue_Kind']) . '</p>
                            <p>' . $VENUE['Venue_Price'] . '</p>
                            <p>' . $VENUE['Venue_Address'] . '</p>
                            <p>' . $VENUE['Venue_Phone'] . '</p>
                        </div>';
                    
                } 
                ?>  </div>
                    
                    <div class="clear" >
                        
                    </div>

                    <form style='padding: 40px; ' method="post">
                        <li>
                            <?php
                            echo '<input type="text" class="btn-large" 
                               name="NAME"
                               value="'.$Booker_Name.'" onfocus="this.value = \'\';" 
                               onblur="if (this.value == \'\') {
                                                       this.value = \'' .$Booker_Name . '\';
                                                   }" ><a href="#" class=" icon user"></a>';
                            ?>
                        </li>

                        <li>
                            <?php
                            echo 'From:<input type="time" class="btn-large" 
                               name="FROM" 
                               value="' .$Booker_From . '" onfocus="this.value = \'\';" 
                               onblur="if (this.value == \'\') {
                                                       this.value = \'' .$Booker_From . '\';
                                                   }" ><a href="#" class=" icon user"></a>
';
                            ?>
                        </li>
                        <li>
                            <?php
                            echo 'To:<input type="time" class="btn-large" 
                               name="TO" 
                               value="' .$Booker_To . '" onfocus="this.value = \'\';" 
                               onblur="if (this.value == \'\') {
                                                       this.value = \'' .$Booker_To . '\';
                                                   }" ><a href="#" class=" icon user"></a>
';
                            ?>
                        </li>
                      <li>
                            <?php
                            echo '<input type="email" class="btn-large" 
                               name="EMAIL" 
                               value="' .$Booker_Email . '" onfocus="this.value = \'\';" 
                               onblur="if (this.value == \'\') {
                                                       this.value = \'' .$Booker_Email . '\';
                                                   }" ><a href="#" class=" icon user"></a>
';
                            ?>
                        </li>
                        <li>
                            <?php
                            echo '<input type="phone" class="btn-large" 
                               name="PHONE" 
                               value="' .$Booker_Phone . '" onfocus="this.value = \'\';" 
                               onblur="if (this.value == \'\') {
                                                       this.value = \'' .$Booker_Phone . '\';
                                                   }" ><a href="#" class=" icon user"></a>
';
                            ?>
                        </li>
                        <div class="p-container">
                            <input name ="submit_book" class ="btn-large" type="submit" 
                                   value="BOOK" >
                            <div class="clear"> </div>
                        </div>
                        <label class="btn-large" style="color: red;	float: none;text-align: center;"><?php if ($message) echo $message; ?></label>

                    </form>
                </div>
            </div>
            <!--//End-login-form-->

            <div id="footer" class="sidebar-right">
                <div class="group inner footer_row_1 footer_cols_3">


                    <div class="sliderWrap">
                        <div class="widget-last widget quick-contact">
                            <h3>Quick Contact</h3>
                            <form id="contact-form-example" class="contact-form" method="post" >
                            <div class="usermessagea"></div>

                            <ul>
                                <li class="text-field">
                                    <label for="name-example">
                                        <text class="label">Name</text>
                                        <input type ="text" name = "mName"></input>
                                    </label>
                                </li>
                                <li class="text-field">
                                    <label for="name-example">
                                        <text class="label">Email</text>
                                        <input type ="text" name = "mEmail"></input>
                                    </label>
                                </li>
                                <li class="textarea-field">
                                    <label for="message-example">
                                        <span class="label">Message</span>
                                        <input type ="text" name = "mMessage" >  </input>
                                    </label>

                                </li>
                                <li class="submit-button">
                                    <input type="submit" name="mSendemail" value="send message" class="sendmail alignright" />			
                                </li>
                            </ul>

                        </form>
                            <script type="text/javascript">
                                var messages_form_footer = {
                                    name: "Insert your name",
                                    email: "Insert your email",
                                    message: "Insert your message"
                                };
                            </script>
                        </div>
                    </div>

                </div>
            </div>


            <!-- START FOOTER -->
            <div id="copyright" class="group">
                <div class="inner group">
                    <div class="left">
                        <p >
                            Copyright <a href="http://wizme.com"><strong>Wizme</strong></a> 2017 -
                            Powered by <a href="http://malloboany.blogspot.com" ><strong>malloboany</strong></a>
                        </p>
                    </div>
                    <div class="right">
                        <a href="http://facebook.com/m.alloboany" class="socials facebook" style="font-size:30px;" title="Facebook">F</a>
                        <a href="#" class="socials twitter" style="font-size:30px;" title="Twitter">L</a>
                        <a href="#" class="socials skype" style="font-size:30px;" title="Skype">H</a>
                        <a href="#" class="socials google" style="font-size:30px;" title="Google">G</a>
                        <a href="#" class="socials linkedin" style="font-size:30px;" title="Linkedin">I</a>
                        <a href="#" class="socials rss" style="font-size:30px;" title="Rss">R</a>
                    </div>
                </div>
            </div>

            <script type="text/javascript" src="js/jquery.custom.js"></script>
            <script type="text/javascript" src="js/contact.js"></script>

            <script type="text/javascript">

                                var _gaq = _gaq || [];
                                _gaq.push(['_setAccount', 'UA-36516261-21']);
                                _gaq.push(['_trackPageview']);

                                (function () {
                                    var ga = document.createElement('script');
                                    ga.type = 'text/javascript';
                                    ga.async = true;
                                    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                                    var s = document.getElementsByTagName('script')[0];
                                    s.parentNode.insertBefore(ga, s);
                                })();

            </script>		
    </body>
</html>